#spring.data.rest.base-path=/api
spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
      url: jdbc:h2:file:./db
      username: sa
      password: 123


  jpa:
    hibernate:
     ddl-auto: create-drop

